LANGUAGES = [
    {"flag": "🇮🇹", "code": "it", "text": "Scegli la tua lingua"},
    {"flag": "🇬🇧", "code": "en", "text": "Choose your language"},
    {"flag": "🇫🇷", "code": "fr", "text": "Choisissez votre langue"},
    {"flag": "🇩🇪", "code": "de", "text": "Wähle deine Sprache"},
    {"flag": "🇪🇸", "code": "es", "text": "Elige tu idioma"},
    {"flag": "🇵🇹", "code": "pt", "text": "Escolha o seu idioma"},
    {"flag": "🇳🇱", "code": "nl", "text": "Kies uw taal"},
    {"flag": "🇬🇷", "code": "el", "text": "Επιλέξτε τη γλώσσα σας"},
    {"flag": "🇷🇴", "code": "ro", "text": "Alegeți limba"},
    {"flag": "🇭🇺", "code": "hu", "text": "Válassza ki a nyelvet"},
    {"flag": "🇵🇱", "code": "pl", "text": "Wybierz swój język"},
    {"flag": "🇨🇿", "code": "cs", "text": "Vyberte jazyk"},
    {"flag": "🇸🇰", "code": "sk", "text": "Vyberte jazyk"},
    {"flag": "🇧🇬", "code": "bg", "text": "Изберете език"},
    {"flag": "🇭🇷", "code": "hr", "text": "Odaberite jezik"},
    {"flag": "🇸🇮", "code": "sl", "text": "Izberite jezik"},
    {"flag": "🇸🇪", "code": "sv", "text": "Välj språk"},
    {"flag": "🇩🇰", "code": "da", "text": "Vælg dit sprog"},
    {"flag": "🇫🇮", "code": "fi", "text": "Valitse kieli"},
    {"flag": "🇪🇪", "code": "et", "text": "Valige keel"},
    {"flag": "🇱🇻", "code": "lv", "text": "Izvēlieties valodu"},
    {"flag": "🇱🇹", "code": "lt", "text": "Pasirinkite kalbą"},
    {"flag": "🇳🇴", "code": "no", "text": "Velg språk"},
    {"flag": "🇮🇪", "code": "ga", "text": "Roghnaigh do theanga"},
    {"flag": "🇲🇹", "code": "mt", "text": "Agħżel il-lingwa tiegħek"},
    {"flag": "🇦🇱", "code": "sq", "text": "Zgjidh gjuhën tënde"},
    {"flag": "🇷🇸", "code": "sr", "text": "Izaberite jezik"},
    {"flag": "🇧🇦", "code": "bs", "text": "Izaberite jezik"},
    {"flag": "🇲🇪", "code": "me", "text": "Izaberite jezik"},
    {"flag": "🇲🇰", "code": "mk", "text": "Изберете јазик"},
    {"flag": "🇹🇷", "code": "tr", "text": "Dilini seç"},
    {"flag": "🇺🇦", "code": "uk", "text": "Оберіть мову"},
    {"flag": "🇧🇾", "code": "be", "text": "Абярыце мову"},
    {"flag": "🇬🇪", "code": "ka", "text": "აირჩიეთ ენა"},
    {"flag": "🇦🇲", "code": "hy", "text": "Ընտրեք լեզուն"},
    {"flag": "🇨🇭", "code": "rm", "text": "Tscherna tia lingua"},
    {"flag": "🇱🇺", "code": "lb", "text": "Wielt Är Sprooch"},
    {"flag": "🇮🇸", "code": "is", "text": "Veldu tungumál"},
    {"flag": "🇦🇩", "code": "ca", "text": "Trieu la vostra llengua"},
    {"flag": "🇷🇺", "code": "ru", "text": "Выберите язык"},
    {"flag": "🇨🇳", "code": "zh", "text": "选择你的语言"},
    {"flag": "🇸🇦", "code": "ar", "text": "اختر لغتك"}
]
