version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./env.example
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: massimo
      POSTGRES_PASSWORD: superpass
      POSTGRES_DB: massimoai

  redis:
    image: redis:7
    ports:
      - "6379:6379"
